
# Site settings
title: Michael Marzec
name: michael marzec
subtitle: assorted attempts at data science(y) projects
email: michaelmarzec11@gmail.com
description:
site_baseurl: "https://michaelmarzec.github.io/"
url: https://michaelmarzec.github.io/
twitter_username: 
github_username:  michaelmarzec
disqus_baseurl: 
disqus_shortname: 
permalink: :title
cover: #"/assets/header_image.jpg"
logo: #"/assets/nr-logo.jpg"
avatar: #"/assets/headshot.jpg"
ga_tracking_id: #"UA-82647777-1"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Michael Marzec"


# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

social:

  - name: GitHub
    icon: github
    username: michaelmarzec
    url: https://github.com/michaelmarzec
    desc: Find me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Michael Marzec
    url: https://www.linkedin.com/in/michael-marzec-16a59294
    desc: Connect with me on LinkedIn
    share: true

