# Dependencies
markdown:         redcarpet
pygments:         true
redcarpet:
  extensions: ["tables"]

# Permalinks
permalink:        pretty

# Setup
title:            Michael Marzec
tagline:          hopefully a blog 11
url:              https://michaelmarzec.github.io/
paginate:         1
baseurl:          /
author:
  name:           Michael Marzec
  url:            espn.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/michaelmarzec/michaelmarzec.github.io

# Header links
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Website: 'https://michaelmarzec.github.io/'
  Feed: '/atom.xml'

